spring:
  application:
    name: socios
  profiles:
    active: test 
server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/