spring:
  application:
    name: socios
  datasource:
    url: jdbc:postgresql://dpg-d90510b7uimc739326p0-a.ohio-postgres.render.com/gym_db_6klh
    username: oscar
    password: HcF3pzAlCU0c7pGoZnzk1Im0d0fLnP7f
    driver-class-name: org.postgresql.Driver
  jpa:
    ddl-auto: update
    show-sql: true

server:
  port: 8081  # <-- Nota: Asegúrate de que use el 8081 en Render si es Socios, para que no choque con tus otros servicios.

# Habilitación técnica de OpenAPI y Swagger UI
springdoc:
  api-docs: 
    enabled: true
  swagger-ui: 
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: https://gym-eureka-server-1.onrender.com/eureka/